spring:
  application:
    name: users
  datasource:
    url: jdbc:h2:mem:users-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
      show-sql: true

password:
  regex: "^(?=.*[A-Z])(?=.*\\d)[A-Za-z\\d]{8,}$"
  message: "The password must be at least 8 characters long, one uppercase character and one number."
